name: themegen
description: A theme generator
version: 0.0.1
homepage: "https://github.com"

# temporary fix
publish_to: 'none'

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  themegen_annotation:
    path: ../themegen_annotation
  source_gen: ^1.2.6
  build: 2.3.1
  analyzer: 5.1.0
  code_builder: 4.3.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.0
  build_runner: 2.2.1

flutter:
