name: themegen
description: A theme generator
version: 0.2.0
homepage: "https://github.com/blazeltd/themegen"

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  themegen_annotation: ^0.0.4
  collection: ^1.16.0
  source_gen: ^1.2.5
  build: ^2.3.1
  analyzer: ^5.1.0
  code_builder: ^4.3.0
  pure: ^0.2.0
  meta: ^1.8.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  purple_lints: ">=0.3.0 <0.5.0"
  build_runner: ^2.2.1

flutter: