name: example
description: Example of using themegen
homepage: "https://github.com/blazeltd/themegen"
publish_to: "none"

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  themegen_annotation: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  themegen:
    path: ../
  build_runner: ^2.2.1
  

flutter:
