on:
  push:
    branches:
      - 'feature/**'
      - 'bugfix/**'
      - 'hotfix/**'
      - 'support/**'
      - 'master'
  workflow_dispatch:

jobs:
  themegen:
    uses: blazeltd/themegen/.github/workflows/shared_checkout.yml@master
    with:
      directory: themegen
  
  themegen_annotation:
    uses: blazeltd/themegen/.github/workflows/shared_checkout.yml@master
    with:
      directory: themegen_annotation

        
      
    