on:
  push:
    branches:
      - 'feature/**'
      - 'bugfix/**'
      - 'hotfix/**'
      - 'support/**'
      - 'master'
  pull_request:
    branches:
      - 'feature/**'
      - 'bugfix/**'
      - 'hotfix/**'
      - 'support/**'
  workflow_dispatch:

jobs:
  test-analyze:
    runs-on: ubuntu-latest
    container:
      image: plugfox/flutter:stable
      options: --user root
    steps:
      - name: 🚂 Get latest code
        uses: actions/checkout@v2

      - name: '🚂 Checkout themegen'
        uses: blazeltd/themegen/.github/workflows/shared_checkout.yml@master
        with:
          directory: themegen
      
      - name: '🚂 Checkout themegen_annotation'
        uses: blazeltd/themegen/.github/workflows/shared_checkout.yml@master
        with:
          directory: themegen_annotation
        
      
    